/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.home.mateusz.jagiela.jagielamateuszprojektobliczenia;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateusz
 */
public class JagielaMateuszProjektObliczenia extends javax.swing.JFrame {

    /**
     * Creates new form JagielaMateuszProjektObliczenia
     */
    public JagielaMateuszProjektObliczenia() {
        initComponents();
        this.setLocationRelativeTo(null); 
        mj_jLabel1.setIcon(new javax.swing.ImageIcon(absolutePathToResources+"1.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mj_buttonGroupDroga = new javax.swing.ButtonGroup();
        mj_buttonGroupTemperatura = new javax.swing.ButtonGroup();
        mj_jPanelMain = new javax.swing.JPanel();
        mj_jTabbedPaneMain = new javax.swing.JTabbedPane();
        mj_jPanel1 = new javax.swing.JPanel();
        mj_jTextField1 = new javax.swing.JTextField();
        mj_jLabelWartosc = new javax.swing.JLabel();
        mj_jRadioButtonMM = new javax.swing.JRadioButton();
        mj_jRadioButtonM = new javax.swing.JRadioButton();
        mj_jRadioButtonKM = new javax.swing.JRadioButton();
        mj_jRadioButtonCM = new javax.swing.JRadioButton();
        mj_jRadioButtonDM = new javax.swing.JRadioButton();
        mj_jLabelWybierzJednostke = new javax.swing.JLabel();
        mj_jTextFieldMM = new javax.swing.JTextField();
        mj_jTextFieldKM = new javax.swing.JTextField();
        mj_jTextFieldM = new javax.swing.JTextField();
        mj_jTextFieldCM = new javax.swing.JTextField();
        mj_jTextFieldDM = new javax.swing.JTextField();
        mj_jLabelMM = new javax.swing.JLabel();
        mj_jLabelM = new javax.swing.JLabel();
        mj_jLabelKM = new javax.swing.JLabel();
        mj_jLabelCM = new javax.swing.JLabel();
        mj_jLabel6 = new javax.swing.JLabel();
        mj_jButtonPrzelicz = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        mj_jPanel2 = new javax.swing.JPanel();
        mj_jRadioButtonK = new javax.swing.JRadioButton();
        mj_jRadioButtonF = new javax.swing.JRadioButton();
        mj_jLabelMM1 = new javax.swing.JLabel();
        mj_jLabelM1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mj_jLabelKM1 = new javax.swing.JLabel();
        mj_jTextFieldC = new javax.swing.JTextField();
        mj_jTextField2 = new javax.swing.JTextField();
        mj_jLabelWartosc1 = new javax.swing.JLabel();
        mj_jButtonPrzelicz1 = new javax.swing.JButton();
        mj_jTextFieldF = new javax.swing.JTextField();
        mj_jRadioButtonC = new javax.swing.JRadioButton();
        mj_jTextFieldK = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        mj_jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mj_jMenuPlik = new javax.swing.JMenu();
        mj_jMenuItemWczytaj = new javax.swing.JMenuItem();
        mj_jMenuItemZamknij = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mj_jMenuItemDroga = new javax.swing.JMenuItem();
        mj_jMenuItemTemp = new javax.swing.JMenuItem();
        mj_jMenuEdit = new javax.swing.JMenu();
        mj_jMenuOprogramie = new javax.swing.JMenu();
        mj_jMenuItemOprogramie = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Przelicznik wartości - Mateusz Jagieła");
        setResizable(false);

        mj_jPanelMain.setBackground(new java.awt.Color(153, 153, 255));

        mj_jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        mj_jLabelWartosc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelWartosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelWartosc.setText("Wpisz wartość");

        mj_buttonGroupDroga.add(mj_jRadioButtonMM);
        mj_jRadioButtonMM.setText("mm");

        mj_buttonGroupDroga.add(mj_jRadioButtonM);
        mj_jRadioButtonM.setText("m");

        mj_buttonGroupDroga.add(mj_jRadioButtonKM);
        mj_jRadioButtonKM.setText("km");

        mj_buttonGroupDroga.add(mj_jRadioButtonCM);
        mj_jRadioButtonCM.setText("cm");

        mj_buttonGroupDroga.add(mj_jRadioButtonDM);
        mj_jRadioButtonDM.setText("dm");

        mj_jLabelWybierzJednostke.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelWybierzJednostke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelWybierzJednostke.setText("Wybierz jednostke");

        mj_jTextFieldMM.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mj_jTextFieldKM.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mj_jTextFieldM.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mj_jTextFieldCM.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mj_jTextFieldDM.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mj_jLabelMM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelMM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelMM.setText("Milimetry");

        mj_jLabelM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelM.setText("Metry");

        mj_jLabelKM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelKM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelKM.setText("Kilometry");

        mj_jLabelCM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelCM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelCM.setText("Centymetry");

        mj_jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabel6.setText("Decymetry");

        mj_jButtonPrzelicz.setText("Przelicz");
        mj_jButtonPrzelicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonPrzeliczActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mj_jPanel1Layout = new javax.swing.GroupLayout(mj_jPanel1);
        mj_jPanel1.setLayout(mj_jPanel1Layout);
        mj_jPanel1Layout.setHorizontalGroup(
            mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mj_jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(mj_jLabelWybierzJednostke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mj_jLabelWartosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mj_jPanel1Layout.createSequentialGroup()
                        .addComponent(mj_jRadioButtonMM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mj_jRadioButtonM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mj_jRadioButtonKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mj_jRadioButtonCM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mj_jRadioButtonDM))
                    .addComponent(mj_jButtonPrzelicz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mj_jTextField1)
                    .addComponent(jSeparator4))
                .addGap(65, 65, 65)
                .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mj_jTextFieldDM)
                        .addComponent(mj_jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mj_jTextFieldCM)
                        .addComponent(mj_jLabelCM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mj_jLabelMM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mj_jTextFieldMM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mj_jTextFieldM)
                            .addComponent(mj_jLabelM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mj_jTextFieldKM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mj_jLabelKM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        mj_jPanel1Layout.setVerticalGroup(
            mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mj_jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jLabelWartosc)
                    .addComponent(mj_jLabelMM))
                .addGap(11, 11, 11)
                .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jTextFieldMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mj_jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(mj_jLabelWybierzJednostke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mj_jRadioButtonMM)
                            .addComponent(mj_jRadioButtonM)
                            .addComponent(mj_jRadioButtonKM)
                            .addComponent(mj_jRadioButtonCM)
                            .addComponent(mj_jRadioButtonDM)))
                    .addGroup(mj_jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mj_jLabelM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mj_jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mj_jLabelKM)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mj_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jTextFieldKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonPrzelicz, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(mj_jLabelCM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mj_jTextFieldCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mj_jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mj_jTextFieldDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        mj_jTabbedPaneMain.addTab("Przelicznik jednostek drogi", mj_jPanel1);

        mj_jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        mj_buttonGroupDroga.add(mj_jRadioButtonK);
        mj_jRadioButtonK.setText("K");

        mj_buttonGroupDroga.add(mj_jRadioButtonF);
        mj_jRadioButtonF.setText("F");

        mj_jLabelMM1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelMM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelMM1.setText("Celcjusza");

        mj_jLabelM1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelM1.setText("Kelvina");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Wybierz jednostke");

        mj_jLabelKM1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelKM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelKM1.setText("Fahrenhaita");

        mj_jTextFieldC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mj_jLabelWartosc1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jLabelWartosc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mj_jLabelWartosc1.setText("Wpisz wartość");

        mj_jButtonPrzelicz1.setText("Przelicz");
        mj_jButtonPrzelicz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonPrzelicz1ActionPerformed(evt);
            }
        });

        mj_jTextFieldF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mj_buttonGroupDroga.add(mj_jRadioButtonC);
        mj_jRadioButtonC.setText("C");

        mj_jTextFieldK.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout mj_jPanel2Layout = new javax.swing.GroupLayout(mj_jPanel2);
        mj_jPanel2.setLayout(mj_jPanel2Layout);
        mj_jPanel2Layout.setHorizontalGroup(
            mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mj_jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mj_jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(mj_jRadioButtonC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mj_jRadioButtonK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mj_jRadioButtonF))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(mj_jLabelWartosc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mj_jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mj_jButtonPrzelicz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6))
                .addGap(66, 66, 66)
                .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mj_jTextFieldK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jLabelM1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jLabelMM1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jLabelKM1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jTextFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        mj_jPanel2Layout.setVerticalGroup(
            mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mj_jPanel2Layout.createSequentialGroup()
                .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mj_jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(mj_jLabelWartosc1)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mj_jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mj_jLabelMM1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mj_jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mj_jRadioButtonC)
                            .addComponent(mj_jRadioButtonK)
                            .addComponent(mj_jRadioButtonF)))
                    .addGroup(mj_jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(mj_jLabelM1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mj_jTextFieldK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mj_jLabelKM1)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mj_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jTextFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonPrzelicz1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        mj_jTabbedPaneMain.addTab("Przelicznik temperatury", mj_jPanel2);

        mj_jLabel1.setText("              //tu sie wyswietla logo");

        javax.swing.GroupLayout mj_jPanelMainLayout = new javax.swing.GroupLayout(mj_jPanelMain);
        mj_jPanelMain.setLayout(mj_jPanelMainLayout);
        mj_jPanelMainLayout.setHorizontalGroup(
            mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mj_jTabbedPaneMain)
            .addComponent(mj_jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mj_jPanelMainLayout.setVerticalGroup(
            mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mj_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mj_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mj_jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mj_jMenuPlik.setText("File");

        mj_jMenuItemWczytaj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mj_jMenuItemWczytaj.setText("Wczytaj");
        mj_jMenuItemWczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jMenuItemWczytajActionPerformed(evt);
            }
        });
        mj_jMenuPlik.add(mj_jMenuItemWczytaj);

        mj_jMenuItemZamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mj_jMenuItemZamknij.setText("Zamknij program");
        mj_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jMenuItemZamknijActionPerformed(evt);
            }
        });
        mj_jMenuPlik.add(mj_jMenuItemZamknij);

        jMenu1.setText("Pokaz Historie");

        mj_jMenuItemDroga.setText("Dla Drogi");
        mj_jMenuItemDroga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jMenuItemDrogaActionPerformed(evt);
            }
        });
        jMenu1.add(mj_jMenuItemDroga);

        mj_jMenuItemTemp.setText("Dla Temperatury");
        mj_jMenuItemTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jMenuItemTempActionPerformed(evt);
            }
        });
        jMenu1.add(mj_jMenuItemTemp);

        mj_jMenuPlik.add(jMenu1);

        jMenuBar1.add(mj_jMenuPlik);

        mj_jMenuEdit.setForeground(new java.awt.Color(153, 153, 153));
        mj_jMenuEdit.setText("Edit");
        jMenuBar1.add(mj_jMenuEdit);

        mj_jMenuOprogramie.setText("O programie");

        mj_jMenuItemOprogramie.setText("O programie");
        mj_jMenuItemOprogramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jMenuItemOprogramieActionPerformed(evt);
            }
        });
        mj_jMenuOprogramie.add(mj_jMenuItemOprogramie);

        jMenuBar1.add(mj_jMenuOprogramie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mj_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mj_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mj_jMenuItemWczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jMenuItemWczytajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mj_jMenuItemWczytajActionPerformed

    private void mj_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jMenuItemZamknijActionPerformed
        this.dispose();
    }//GEN-LAST:event_mj_jMenuItemZamknijActionPerformed

    private void mj_jMenuItemOprogramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jMenuItemOprogramieActionPerformed
        JOptionPane.showMessageDialog(this,"<html>Aplikacja wykonana przez<br> Mateusza Jagieła, 2PTN<html>");
    }//GEN-LAST:event_mj_jMenuItemOprogramieActionPerformed

    private void mj_jButtonPrzeliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonPrzeliczActionPerformed
        JednostkiDrogi();
        saveSettingsDroga();
    }//GEN-LAST:event_mj_jButtonPrzeliczActionPerformed

    private void mj_jButtonPrzelicz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonPrzelicz1ActionPerformed
        PrzelicznikTemp();
        saveSettingsTemp();
    }//GEN-LAST:event_mj_jButtonPrzelicz1ActionPerformed

    private void mj_jMenuItemDrogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jMenuItemDrogaActionPerformed
        HistoriaDrogi();
    }//GEN-LAST:event_mj_jMenuItemDrogaActionPerformed

    private void mj_jMenuItemTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jMenuItemTempActionPerformed
        HistoriaTemperatury();
    }//GEN-LAST:event_mj_jMenuItemTempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszProjektObliczenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszProjektObliczenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszProjektObliczenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszProjektObliczenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JagielaMateuszProjektObliczenia().setVisible(true);
            }
        });
    }

    String absolutePathToResources="src\\main\\\\java\\\\pl\\\\home\\\\mateusz\\\\jagiela\\\\jagielamateuszprojektobliczenia\\\\resources\\\\";
    
    //funkcje
    
    private void HistoriaTemperatury(){
        JFileChooser wyb_pliku = new JFileChooser();
        File f = new File("Temperatura_MJ.txt");
        try {
            String Tekst = "";
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                Tekst = Tekst+"\n"+sc.nextLine();
        }
            JOptionPane.showMessageDialog(this,Tekst);    
    }
        catch(FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }   
    
    private void HistoriaDrogi(){
        JFileChooser wyb_pliku = new JFileChooser();
        File f = new File("Droga_MJ.txt");
        try {
            String Tekst = "";
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                Tekst = Tekst+"\n"+sc.nextLine();
        }
            JOptionPane.showMessageDialog(this,Tekst);    
    }
        catch(FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }    
    
    private void saveSettingsTemp(){
        try{
           File f = new File("Temperatura_MJ.txt");  
           FileWriter fw = new FileWriter(f);          
            String a = (String) mj_jTextFieldC.getText();
            String b = (String) mj_jTextFieldK.getText();
            String c = (String) mj_jTextFieldF.getText();
            String temp = "N";
            if(mj_jRadioButtonC.isSelected()){
                temp = "Celcjusza";
            }else if(mj_jRadioButtonK.isSelected()){
                temp = "Kelvina";
            }else if(mj_jRadioButtonF.isSelected()){
                temp = "Fahrenhaita";
            }
            fw.write("Przeliczasz z "+temp+"\n\n"+"Celcjusza: "+a+"\nKelvina: "+b+"\nFahrenhaita: "+c+"");
            fw.close();
           }catch(IOException e){
            System.out.println("Błąd: "+e.toString());
           }
    }
    
    private void saveSettingsDroga(){
        try{
           File f = new File("Droga_MJ.txt");  
           FileWriter fw = new FileWriter(f);          
            String a = (String) mj_jTextFieldMM.getText();
            String b = (String) mj_jTextFieldM.getText();
            String c = (String) mj_jTextFieldKM.getText();
            String d = (String) mj_jTextFieldCM.getText();
            String e = (String) mj_jTextFieldDM.getText();
            String droga = "N";
            if(mj_jRadioButtonMM.isSelected()){
                droga = "Milimetrow";
            }else if(mj_jRadioButtonM.isSelected()){
                droga = "Metrow";
            }else if(mj_jRadioButtonKM.isSelected()){
                droga = "Kilometrow";
            }else if(mj_jRadioButtonCM.isSelected()){
                droga = "Centymetrow";
            }else if(mj_jRadioButtonDM.isSelected()){
                droga = "Decymetrow";    
            }
            fw.write("Przeliczasz z "+droga+"\n\n"+"Milimetry: "+a+"\nMetry: "+b+"\nKilometry: "+c+"\nCentymetry: "+d+"\nDecymetry: "+e);
            fw.close();
           }catch(IOException e){
            System.out.println("Błąd: "+e.toString());
           }
    }
    
    public void PrzelicznikTemp(){
        String wpisana = mj_jTextField2.getText();
        Double zmieniona = Double.parseDouble(wpisana);
        if(mj_jRadioButtonC.isSelected()){
            String C=Double.toString(zmieniona);
            String K=Double.toString(zmieniona+273);
            String F=Double.toString((zmieniona*9/5)+32);
            
                mj_jTextFieldC.setText(""+C);
                mj_jTextFieldK.setText(""+K);
                mj_jTextFieldF.setText(""+F);
            
        }else if(mj_jRadioButtonK.isSelected()){
            String C=Double.toString(zmieniona-273);
            String K=Double.toString(zmieniona);
            String F=Double.toString(((zmieniona-273)*9/5)+32);
            
                mj_jTextFieldC.setText(""+C);
                mj_jTextFieldK.setText(""+K);
                mj_jTextFieldF.setText(""+F);
            
        }else if(mj_jRadioButtonF.isSelected()){
            String C=Double.toString(5*(zmieniona - 32)/9);
            String K=Double.toString(zmieniona);
            String F=Double.toString(zmieniona);
            
                mj_jTextFieldC.setText(""+C);
                mj_jTextFieldK.setText(""+K);
                mj_jTextFieldF.setText(""+F);
            
        }
    }
    
    public void JednostkiDrogi(){ 
        String wprowadzona = mj_jTextField1.getText();
        Double elegancka = Double.parseDouble(wprowadzona);
            
        if(mj_jRadioButtonMM.isSelected()){
            String mm=Double.toString(elegancka);
            String cm=Double.toString(elegancka*0.1);
            String dm=Double.toString(elegancka*0.01);
            String m=Double.toString(elegancka*0.001);
            String km=Double.toString(elegancka*0.000001);
            
                mj_jTextFieldMM.setText(""+mm);
                mj_jTextFieldCM.setText(""+cm);
                mj_jTextFieldDM.setText(""+dm);
                mj_jTextFieldM.setText(""+m);
                mj_jTextFieldKM.setText(""+km);
            
        }else if(mj_jRadioButtonCM.isSelected()){
            String mm=Double.toString(elegancka*10);
            String cm=Double.toString(elegancka);
            String dm=Double.toString(elegancka*0.1);
            String m=Double.toString(elegancka*0.01);
            String km=Double.toString(elegancka*0.00001);
            
                mj_jTextFieldMM.setText(""+mm);
                mj_jTextFieldCM.setText(""+cm);
                mj_jTextFieldDM.setText(""+dm);
                mj_jTextFieldM.setText(""+m);
                mj_jTextFieldKM.setText(""+km);
            
        }else if(mj_jRadioButtonDM.isSelected()){
            String mm=Double.toString(elegancka*100);
            String cm=Double.toString(elegancka*10);
            String dm=Double.toString(elegancka);
            String m=Double.toString(elegancka*0.1);
            String km=Double.toString(elegancka*0.0001);
            
                mj_jTextFieldMM.setText(""+mm);
                mj_jTextFieldCM.setText(""+cm);
                mj_jTextFieldDM.setText(""+dm);
                mj_jTextFieldM.setText(""+m);
                mj_jTextFieldKM.setText(""+km);
            
        }else if(mj_jRadioButtonM.isSelected()){
            String mm=Double.toString(elegancka*1000);
            String cm=Double.toString(elegancka*100);
            String dm=Double.toString(elegancka*10);
            String m=Double.toString(elegancka);
            String km=Double.toString(elegancka*0.001);
            
                mj_jTextFieldMM.setText(""+mm);
                mj_jTextFieldCM.setText(""+cm);
                mj_jTextFieldDM.setText(""+dm);
                mj_jTextFieldM.setText(""+m);
                mj_jTextFieldKM.setText(""+km);
            
        }else if(mj_jRadioButtonKM.isSelected()){
            String mm=Double.toString(elegancka*1000000);
            String cm=Double.toString(elegancka*100000);
            String dm=Double.toString(elegancka*10000);
            String m=Double.toString(elegancka*1000);
            String km=Double.toString(elegancka);
            
                mj_jTextFieldMM.setText(""+mm);
                mj_jTextFieldCM.setText(""+cm);
                mj_jTextFieldDM.setText(""+dm);
                mj_jTextFieldM.setText(""+m);
                mj_jTextFieldKM.setText(""+km);
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.ButtonGroup mj_buttonGroupDroga;
    private javax.swing.ButtonGroup mj_buttonGroupTemperatura;
    private javax.swing.JButton mj_jButtonPrzelicz;
    private javax.swing.JButton mj_jButtonPrzelicz1;
    private javax.swing.JLabel mj_jLabel1;
    private javax.swing.JLabel mj_jLabel6;
    private javax.swing.JLabel mj_jLabelCM;
    private javax.swing.JLabel mj_jLabelKM;
    private javax.swing.JLabel mj_jLabelKM1;
    private javax.swing.JLabel mj_jLabelM;
    private javax.swing.JLabel mj_jLabelM1;
    private javax.swing.JLabel mj_jLabelMM;
    private javax.swing.JLabel mj_jLabelMM1;
    private javax.swing.JLabel mj_jLabelWartosc;
    private javax.swing.JLabel mj_jLabelWartosc1;
    private javax.swing.JLabel mj_jLabelWybierzJednostke;
    private javax.swing.JMenu mj_jMenuEdit;
    private javax.swing.JMenuItem mj_jMenuItemDroga;
    private javax.swing.JMenuItem mj_jMenuItemOprogramie;
    private javax.swing.JMenuItem mj_jMenuItemTemp;
    private javax.swing.JMenuItem mj_jMenuItemWczytaj;
    private javax.swing.JMenuItem mj_jMenuItemZamknij;
    private javax.swing.JMenu mj_jMenuOprogramie;
    private javax.swing.JMenu mj_jMenuPlik;
    private javax.swing.JPanel mj_jPanel1;
    private javax.swing.JPanel mj_jPanel2;
    private javax.swing.JPanel mj_jPanelMain;
    private javax.swing.JRadioButton mj_jRadioButtonC;
    private javax.swing.JRadioButton mj_jRadioButtonCM;
    private javax.swing.JRadioButton mj_jRadioButtonDM;
    private javax.swing.JRadioButton mj_jRadioButtonF;
    private javax.swing.JRadioButton mj_jRadioButtonK;
    private javax.swing.JRadioButton mj_jRadioButtonKM;
    private javax.swing.JRadioButton mj_jRadioButtonM;
    private javax.swing.JRadioButton mj_jRadioButtonMM;
    private javax.swing.JTabbedPane mj_jTabbedPaneMain;
    private javax.swing.JTextField mj_jTextField1;
    private javax.swing.JTextField mj_jTextField2;
    private javax.swing.JTextField mj_jTextFieldC;
    private javax.swing.JTextField mj_jTextFieldCM;
    private javax.swing.JTextField mj_jTextFieldDM;
    private javax.swing.JTextField mj_jTextFieldF;
    private javax.swing.JTextField mj_jTextFieldK;
    private javax.swing.JTextField mj_jTextFieldKM;
    private javax.swing.JTextField mj_jTextFieldM;
    private javax.swing.JTextField mj_jTextFieldMM;
    // End of variables declaration//GEN-END:variables
}
