/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.home.mateusz.jagiela.jagielamateuszkalkulator;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateusz
 */
public class JagielaMateuszKalkulator extends javax.swing.JFrame {

    double pierwszaliczba;
    double drugaliczba;
    double wynik;
    String operatory;
   
    
    /**
     * Creates new form JagielaMateuszKalkulator
     */
    public JagielaMateuszKalkulator() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mj_jPanelMain = new javax.swing.JPanel();
        mj_jTextFieldMain = new javax.swing.JTextField();
        mj_jButton1 = new javax.swing.JButton();
        mj_jButton2 = new javax.swing.JButton();
        mj_jButton3 = new javax.swing.JButton();
        mj_jButton4 = new javax.swing.JButton();
        mj_jButton5 = new javax.swing.JButton();
        mj_jButton6 = new javax.swing.JButton();
        mj_jButton7 = new javax.swing.JButton();
        mj_jButton8 = new javax.swing.JButton();
        mj_jButton9 = new javax.swing.JButton();
        mj_jButton0 = new javax.swing.JButton();
        mj_jButtonPlus = new javax.swing.JButton();
        mj_jButtonMinus = new javax.swing.JButton();
        mj_jButtonDzielenie = new javax.swing.JButton();
        mj_jButtonMnozenie = new javax.swing.JButton();
        mj_jButtonPM = new javax.swing.JButton();
        mj_jButtonKropka = new javax.swing.JButton();
        mj_jButtonWynik = new javax.swing.JButton();
        mj_jButtonC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mj_jButtonC1 = new javax.swing.JButton();
        mj_jButtonPotegowanie = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mj_jMenuBar1 = new javax.swing.JMenuBar();
        mj_Kalkulator = new javax.swing.JMenu();
        mj_Zapisz = new javax.swing.JMenuItem();
        mj_Zamknij = new javax.swing.JMenuItem();
        mj_Historia = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mj_jCheckBoxMenuZapis = new javax.swing.JCheckBoxMenuItem();
        mj_Separator = new javax.swing.JPopupMenu.Separator();
        mj_Info = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator - MJ");
        setResizable(false);

        mj_jPanelMain.setBackground(new java.awt.Color(0, 0, 0));

        mj_jTextFieldMain.setBackground(new java.awt.Color(51, 51, 51));
        mj_jTextFieldMain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jTextFieldMain.setForeground(new java.awt.Color(255, 255, 255));
        mj_jTextFieldMain.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        mj_jButton1.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton1.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton1.setText("1");
        mj_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton1ActionPerformed(evt);
            }
        });

        mj_jButton2.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton2.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton2.setText("2");
        mj_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton2ActionPerformed(evt);
            }
        });

        mj_jButton3.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton3.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton3.setText("3");
        mj_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton3ActionPerformed(evt);
            }
        });

        mj_jButton4.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton4.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton4.setText("4");
        mj_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton4ActionPerformed(evt);
            }
        });

        mj_jButton5.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton5.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton5.setText("5");
        mj_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton5ActionPerformed(evt);
            }
        });

        mj_jButton6.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton6.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton6.setText("6");
        mj_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton6ActionPerformed(evt);
            }
        });

        mj_jButton7.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton7.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton7.setText("7");
        mj_jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton7ActionPerformed(evt);
            }
        });

        mj_jButton8.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton8.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton8.setText("8");
        mj_jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton8ActionPerformed(evt);
            }
        });

        mj_jButton9.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton9.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton9.setText("9");
        mj_jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton9ActionPerformed(evt);
            }
        });

        mj_jButton0.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButton0.setForeground(new java.awt.Color(255, 255, 255));
        mj_jButton0.setText("0");
        mj_jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButton0ActionPerformed(evt);
            }
        });

        mj_jButtonPlus.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonPlus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonPlus.setForeground(new java.awt.Color(255, 153, 0));
        mj_jButtonPlus.setText("+");
        mj_jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonPlusActionPerformed(evt);
            }
        });

        mj_jButtonMinus.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonMinus.setForeground(new java.awt.Color(255, 153, 51));
        mj_jButtonMinus.setText("-");
        mj_jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonMinusActionPerformed(evt);
            }
        });

        mj_jButtonDzielenie.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonDzielenie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonDzielenie.setForeground(new java.awt.Color(255, 102, 0));
        mj_jButtonDzielenie.setText("/");
        mj_jButtonDzielenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonDzielenieActionPerformed(evt);
            }
        });

        mj_jButtonMnozenie.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonMnozenie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonMnozenie.setForeground(new java.awt.Color(255, 102, 0));
        mj_jButtonMnozenie.setText("*");
        mj_jButtonMnozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonMnozenieActionPerformed(evt);
            }
        });

        mj_jButtonPM.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonPM.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonPM.setForeground(new java.awt.Color(255, 102, 0));
        mj_jButtonPM.setText("+/-");
        mj_jButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonPMActionPerformed(evt);
            }
        });

        mj_jButtonKropka.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonKropka.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonKropka.setForeground(new java.awt.Color(255, 102, 0));
        mj_jButtonKropka.setText(".");
        mj_jButtonKropka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonKropkaActionPerformed(evt);
            }
        });

        mj_jButtonWynik.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonWynik.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonWynik.setForeground(new java.awt.Color(255, 51, 0));
        mj_jButtonWynik.setText("=");
        mj_jButtonWynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonWynikActionPerformed(evt);
            }
        });

        mj_jButtonC.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mj_jButtonC.setForeground(new java.awt.Color(255, 51, 0));
        mj_jButtonC.setText("C");
        mj_jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mateusz Jagiela");

        mj_jButtonC1.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonC1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mj_jButtonC1.setForeground(new java.awt.Color(255, 51, 0));
        mj_jButtonC1.setText("Pierwiastek");
        mj_jButtonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonC1ActionPerformed(evt);
            }
        });

        mj_jButtonPotegowanie.setBackground(new java.awt.Color(0, 0, 0));
        mj_jButtonPotegowanie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mj_jButtonPotegowanie.setForeground(new java.awt.Color(255, 51, 0));
        mj_jButtonPotegowanie.setText("X²");
        mj_jButtonPotegowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_jButtonPotegowanieActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Niezbędne informacje można znaleść w zakładce wyżej");

        javax.swing.GroupLayout mj_jPanelMainLayout = new javax.swing.GroupLayout(mj_jPanelMain);
        mj_jPanelMain.setLayout(mj_jPanelMainLayout);
        mj_jPanelMainLayout.setHorizontalGroup(
            mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mj_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mj_jPanelMainLayout.createSequentialGroup()
                        .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mj_jPanelMainLayout.createSequentialGroup()
                                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mj_jButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(mj_jButtonDzielenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mj_jButtonWynik, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(mj_jButtonMnozenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mj_jButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(mj_jButtonC1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mj_jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mj_jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mj_jButtonKropka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mj_jButtonPotegowanie, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                            .addGroup(mj_jPanelMainLayout.createSequentialGroup()
                                .addComponent(mj_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mj_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mj_jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mj_jPanelMainLayout.createSequentialGroup()
                                .addComponent(mj_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mj_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mj_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mj_jTextFieldMain)
                                .addGroup(mj_jPanelMainLayout.createSequentialGroup()
                                    .addComponent(mj_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mj_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mj_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mj_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mj_jPanelMainLayout.setVerticalGroup(
            mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mj_jPanelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(mj_jTextFieldMain, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mj_jButtonDzielenie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonMnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonKropka, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mj_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mj_jButtonWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mj_jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mj_jButtonC1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mj_jButtonPotegowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mj_Kalkulator.setText("Kalkulator");

        mj_Zapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mj_Zapisz.setText("Zapisz");
        mj_Zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_ZapiszActionPerformed(evt);
            }
        });
        mj_Kalkulator.add(mj_Zapisz);

        mj_Zamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mj_Zamknij.setText("Zamknij");
        mj_Zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_ZamknijActionPerformed(evt);
            }
        });
        mj_Kalkulator.add(mj_Zamknij);

        mj_Historia.setText("Historia");
        mj_Historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_HistoriaActionPerformed(evt);
            }
        });
        mj_Kalkulator.add(mj_Historia);
        mj_Kalkulator.add(jSeparator1);

        mj_jCheckBoxMenuZapis.setSelected(true);
        mj_jCheckBoxMenuZapis.setText("Włącz / Wyłącz zapis");
        mj_Kalkulator.add(mj_jCheckBoxMenuZapis);
        mj_Kalkulator.add(mj_Separator);

        mj_Info.setText("Informacje");
        mj_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mj_InfoActionPerformed(evt);
            }
        });
        mj_Kalkulator.add(mj_Info);

        mj_jMenuBar1.add(mj_Kalkulator);

        setJMenuBar(mj_jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mj_jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mj_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mj_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton1ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton1.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton1ActionPerformed

    private void mj_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton2ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton2.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton2ActionPerformed

    private void mj_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton3ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton3.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton3ActionPerformed

    private void mj_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton4ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton4.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton4ActionPerformed

    private void mj_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton5ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton5.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton5ActionPerformed

    private void mj_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton6ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton6.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton6ActionPerformed

    private void mj_jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton7ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton7.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton7ActionPerformed

    private void mj_jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton8ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton8.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton8ActionPerformed

    private void mj_jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton9ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton9.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton9ActionPerformed

    private void mj_jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButton0ActionPerformed
        String WpisLicz = mj_jTextFieldMain.getText() + mj_jButton0.getText();
        mj_jTextFieldMain.setText(WpisLicz);
    }//GEN-LAST:event_mj_jButton0ActionPerformed

    private void mj_jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonPlusActionPerformed
        pierwszaliczba = Double.parseDouble(mj_jTextFieldMain.getText());
        mj_jTextFieldMain.setText("");
        operatory = "+";
    }//GEN-LAST:event_mj_jButtonPlusActionPerformed

    private void mj_jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonMinusActionPerformed
        pierwszaliczba = Double.parseDouble(mj_jTextFieldMain.getText());
        mj_jTextFieldMain.setText("");
        operatory = "-";
    }//GEN-LAST:event_mj_jButtonMinusActionPerformed

    private void mj_jButtonDzielenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonDzielenieActionPerformed
        pierwszaliczba = Double.parseDouble(mj_jTextFieldMain.getText());
        mj_jTextFieldMain.setText("");
        operatory = "/";
    }//GEN-LAST:event_mj_jButtonDzielenieActionPerformed

    private void mj_jButtonMnozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonMnozenieActionPerformed
        pierwszaliczba = Double.parseDouble(mj_jTextFieldMain.getText());
        mj_jTextFieldMain.setText("");
        operatory = "*";
    }//GEN-LAST:event_mj_jButtonMnozenieActionPerformed

    private void mj_jButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonPMActionPerformed
        double ops = Double.parseDouble(String.valueOf(mj_jTextFieldMain.getText()));
        ops = ops * (-1);
        mj_jTextFieldMain.setText(String.valueOf(ops));
    }//GEN-LAST:event_mj_jButtonPMActionPerformed

    private void mj_jButtonKropkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonKropkaActionPerformed
        mj_jTextFieldMain.setText(mj_jTextFieldMain.getText() + ".");
    }//GEN-LAST:event_mj_jButtonKropkaActionPerformed

    private void mj_jButtonWynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonWynikActionPerformed
        String odp;
        drugaliczba = Double.parseDouble(mj_jTextFieldMain.getText());
        if (operatory == "+"){
            wynik = pierwszaliczba + drugaliczba;
            odp = String.format("%.0f",wynik);
            mj_jTextFieldMain.setText(odp);
            
        }else if (operatory == "-"){
            wynik = pierwszaliczba - drugaliczba;
            odp = String.format("%.0f",wynik);
            mj_jTextFieldMain.setText(odp);
            
        }else if (operatory == "*"){
            wynik = pierwszaliczba * drugaliczba;
            odp = String.format("%.0f",wynik);
            mj_jTextFieldMain.setText(odp);
            
        }else if (operatory == "/"){
            wynik = pierwszaliczba / drugaliczba;
            odp = String.format("%.0f",wynik);
            mj_jTextFieldMain.setText(odp);
            if(drugaliczba==0){
                mj_jTextFieldMain.setText("Błąd: Nie dziel przez 0");
            }
            
        }else if (operatory == "%"){
            wynik = pierwszaliczba % drugaliczba;
            odp = String.format("%.0f",wynik);
            mj_jTextFieldMain.setText(odp); 
        
        }else if (operatory == "^"){
            wynik = pierwszaliczba * pierwszaliczba;
            odp = String.format("%.0f",wynik);
            mj_jTextFieldMain.setText(odp);
            if(pierwszaliczba==0){
                mj_jTextFieldMain.setText("Błąd: Nie potęguj przez 0");
            }
            
        }
        
    }//GEN-LAST:event_mj_jButtonWynikActionPerformed

    private void mj_jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonCActionPerformed
        mj_jTextFieldMain.setText("");
    }//GEN-LAST:event_mj_jButtonCActionPerformed

    private void mj_ZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_ZamknijActionPerformed
        this.dispose();
    }//GEN-LAST:event_mj_ZamknijActionPerformed

    private void mj_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_InfoActionPerformed
        JOptionPane.showMessageDialog(this,"<html>Aplikacja wykonana przez Mateusz Jagieła.<br>"
                + "Kalkulator ma automatyczne zaokrąglanie liczb.<br>"
                + "Potęgowanie jest tylko drugiego stopnia.<br>"
                + "<html>");
    }//GEN-LAST:event_mj_InfoActionPerformed

    private void mj_jButtonC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonC1ActionPerformed
        pierwszaliczba = Double.parseDouble(mj_jTextFieldMain.getText());
        double sqrt = Math.sqrt(pierwszaliczba);
        mj_jTextFieldMain.setText(String.valueOf(sqrt));
    }//GEN-LAST:event_mj_jButtonC1ActionPerformed

    private void mj_HistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_HistoriaActionPerformed
        historia();
    }//GEN-LAST:event_mj_HistoriaActionPerformed

    private void mj_jButtonPotegowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_jButtonPotegowanieActionPerformed
        pierwszaliczba = Double.parseDouble(mj_jTextFieldMain.getText());
        mj_jTextFieldMain.setText("");
        operatory = "^";
    }//GEN-LAST:event_mj_jButtonPotegowanieActionPerformed

    private void mj_ZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mj_ZapiszActionPerformed
       if(mj_jCheckBoxMenuZapis.isSelected()){ 
            zapis();
       }
    }//GEN-LAST:event_mj_ZapiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JagielaMateuszKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JagielaMateuszKalkulator().setVisible(true);
            }
        });
    }
    
    private void zapis(){
        File f = new File("zapis.txt");
        FileWriter fw;
        try {
            fw = new FileWriter(f,true);
            fw.append(""+mj_jTextFieldMain.getText()+"; ");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(JagielaMateuszKalkulator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void historia(){
        File f = new File("zapis.txt");
        try {
            String Tekst = "";
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                Tekst = Tekst+"\n"+sc.nextLine();
            }
            JOptionPane.showMessageDialog(this,Tekst,"Historia",JOptionPane.PLAIN_MESSAGE);
        }
        catch(FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mj_Historia;
    private javax.swing.JMenuItem mj_Info;
    private javax.swing.JMenu mj_Kalkulator;
    private javax.swing.JPopupMenu.Separator mj_Separator;
    private javax.swing.JMenuItem mj_Zamknij;
    private javax.swing.JMenuItem mj_Zapisz;
    private javax.swing.JButton mj_jButton0;
    private javax.swing.JButton mj_jButton1;
    private javax.swing.JButton mj_jButton2;
    private javax.swing.JButton mj_jButton3;
    private javax.swing.JButton mj_jButton4;
    private javax.swing.JButton mj_jButton5;
    private javax.swing.JButton mj_jButton6;
    private javax.swing.JButton mj_jButton7;
    private javax.swing.JButton mj_jButton8;
    private javax.swing.JButton mj_jButton9;
    private javax.swing.JButton mj_jButtonC;
    private javax.swing.JButton mj_jButtonC1;
    private javax.swing.JButton mj_jButtonDzielenie;
    private javax.swing.JButton mj_jButtonKropka;
    private javax.swing.JButton mj_jButtonMinus;
    private javax.swing.JButton mj_jButtonMnozenie;
    private javax.swing.JButton mj_jButtonPM;
    private javax.swing.JButton mj_jButtonPlus;
    private javax.swing.JButton mj_jButtonPotegowanie;
    private javax.swing.JButton mj_jButtonWynik;
    private javax.swing.JCheckBoxMenuItem mj_jCheckBoxMenuZapis;
    private javax.swing.JMenuBar mj_jMenuBar1;
    private javax.swing.JPanel mj_jPanelMain;
    private javax.swing.JTextField mj_jTextFieldMain;
    // End of variables declaration//GEN-END:variables
}
